---

- name: ppas
  apt_repository: "repo='{{ item }}'"
  with_items:
    # screenshots
    - "ppa:shutter/ppa"
    # atom text editor
    - "ppa:webupd8team/atom"

- name: update-cache
  apt: update_cache=yes

- name: install
  apt: pkg={{ item }}
  with_items:
    # commonly used applications with restricted copyright
    - ubuntu-restricted-extras
    # media player
    - vlc
    # required to convert ovgs into a gif
    - mplayer
    # finance manager
    - gnucash
    # password manager
    - keepassx
    # image editor
    - gimp
    # desktop recording
    - gtk-recordmydesktop
    # system monitor
    - gnome-system-monitor
    # torrents
    - transmission
    # radio
    - radiotray
    # screenshot tool
    - shutter
    # diff viewer
    - meld
    # download manager
    - steadyflow
    # required by electrum
    - python-slowaes
    # partition management
    - gparted
    # pdf anotations
    - xournal
    # ebook manager
    - calibre
    # ftp
    - filezilla
    # reload display configurations
    - disper
    # atom text editor
    - atom
    # VPN
    - openvpn

- name: debs
  get_url: url={{ item }} dest=/tmp force=no
  with_items:
    - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - https://dl.google.com/linux/direct/google-talkplugin_current_amd64.deb
    - https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb
    - https://downloads.slack-edge.com/linux_releases/slack-desktop-2.0.3-amd64.deb

- name: install debs
  command: dpkg --skip-same-version -i /tmp/{{ item }}
  register: dpkg_result
  changed_when: "dpkg_result.stdout.startswith('Selecting')"
  with_items:
    # Google Chrome browser
    - google-chrome-stable_current_amd64.deb
    # Google Talk
    - google-talkplugin_current_amd64.deb
    # Dropbox
    - dropbox_2015.10.28_amd64.deb
    # Slack
    - slack-desktop-2.0.3-amd64.deb

- name: pip
  pip: name={{ item }}
  with_items:
    # electrum bitcoin wallet
    - https://download.electrum.org/2.6.4/Electrum-2.6.4.tar.gz
