---

- name: ppas
  apt_repository: repo={{ item }}
  with_items:
    # sublime text editor
    - "ppa:webupd8team/sublime-text-3"
    # screenshots
    - "ppa:shutter/ppa"

- name: install
  apt: pkg={{ item }}
  with_items:
    # sublime text editor
    - sublime-text-installer
    # commonly used applications with restricted copyright
    - ubuntu-restricted-extras
    # flash player
    - flashplugin-installer
    # media player
    - vlc
    # chat client
    - pidgin
    # finance manager
    - gnucash
    # password manager
    - keepassx
    # image editor
    - gimp
    # desktop recording
    - gtk-recordmydesktop
    # system monitor
    - gnome-system-monitor
    # backups
    - deja-dup
    # torrents
    - transmission
    # radio
    - radiotray
    # screenshot tool
    - shutter
    # subtitles download
    - subdownloader

- name: debs
  get_url: url={{ item }} dest=/tmp
  with_items:
    - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_1.6.0_amd64.deb

- name: install debs
  command: dpkg --skip-same-version -i /tmp/{{ item }}
  register: dpkg_result
  changed_when: "dpkg_result.stdout.startswith('Selecting')"
  with_items:
    # Google Chrome browser
    - google-chrome-stable_current_amd64.deb
    # Dropbox
    - dropbox_1.6.0_amd64.deb

- name: pip
  pip: name={{ item }}
  with_items:
    # electrum bitcoin wallet
    - http://download.electrum.org/Electrum-1.9.5.tar.gz#md5=e8d66b08f7d1d745e1de04a090d199c2
