---

- name: ubuntu distribution
  shell: "grep '^deb ' /etc/apt/sources.list | head -n1 | awk '{ print $3 }'"
  register: codename
  changed_when: False

- name: ppas
  apt_repository: repo={{ item }}
  with_items:
    # jdk
    -  "ppa:webupd8team/java"
    # git
    -  "ppa:git-core/ppa"

- name: postgres ppa key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: passenger ppa key
  apt_key: id=AC40B2F7 state=present url="http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x561F9B9CAC40B2F7"

- name: postgres ppa
  apt_repository: "repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'"

- name: passenger ppa
  apt_repository: "repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ codename.stdout }} main'"

- name: oracle auto accept select
  shell: "echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections"
  changed_when: False

- name: oracle auto accept seen
  shell: "echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections"
  changed_when: False

- name: install
  apt: pkg={{ item }}
  with_items:
    # build essential
    - build-essential
    # automatic configure script builder
    - autoconf
    # compilation
    - make
    # makefiles
    - automake

    # ssl headers - required for ruby-build
    - libssl-dev
    # yaml headers - required for ruby-build
    - libyaml-dev
    # readline - required for ruby-build
    - libreadline6
    # readline dev - required for ruby-build
    - libreadline6-dev
    # compression lib - required for ruby-build
    - zlib1g
    # compression lib headers - required for ruby-build
    - zlib1g-dev
    # image processing
    - imagemagick

    # node javascript runtime
    - nodejs

    # jdk
    - oracle-java8-installer
    # java web plugin
    - icedtea-plugin

    # git source control
    - git
    # git graphical interface
    - gitg
    # subversion source control
    - subversion
    # bazaar source control
    - bzr

    # english dict lib
    - wamerican

    # sqlite database
    - sqlite3
    # slite lib
    - libsqlite3-0
    # sqlite driver header
    - libsqlite3-dev

    # mysql database
    - mysql-server
    # mysql gui
    - mysql-workbench
    # mysql driver lib
    - libmysqlclient-dev
    # mysql ruby driver lib
    - libmysql-ruby

    # postgres database
    - postgresql-9.3
    # postgres extensions
    - postgresql-contrib-9.3
    # postgres driver lib
    - libpq-dev
    # postgres gui
    - pgadmin3
    # ansible postgres integration
    - python-psycopg2

    # redis key-value database
    - redis-server

    # nginx web server
    - nginx-extras

    # nginx passenger ruby module
    - passenger

- name: postgres user
  postgresql_user: name={{ user }} password={{ user }} role_attr_flags=SUPERUSER
  sudo_user: postgres

- name: postgres encoding facts
  shell: "psql -c \"SELECT datname FROM pg_database WHERE encoding = pg_char_to_encoding('UTF8') AND datcollate = 'en_US.utf8' AND datctype = 'en_US.utf8'\""
  sudo_user: postgres
  register: postgres_encoding
  changed_when: False

- name: postgres encoding
  when: "postgres_encoding.stdout.find('template1') == -1"
  shell: "psql -c \"UPDATE pg_database SET encoding = pg_char_to_encoding('UTF8'), datcollate = 'en_US.utf8', datctype = 'en_US.utf8' WHERE datname = 'template1';\""
  sudo_user: postgres

- name: passenger nginx config
  template: src=nginx.j2 dest=/etc/nginx/nginx.conf
