---

- name: node repository key
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: node repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_5.x ubuntu-{{ ansible_distribution_release }} main"
    update_cache: yes
    state: present

- name: nodejs package
  apt: pkg=nodejs
