---

- name: vagrant deb
  get_url: url={{ item }} dest=/tmp force=no
  with_items:
    - https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb

- name: vagrant install
  command: dpkg --skip-same-version -i /tmp/{{ item }}
  register: dpkg_result
  changed_when: "dpkg_result.stdout.startswith('Selecting')"
  with_items:
    - vagrant_1.8.1_x86_64.deb
